select * from [registrationdb].[dbo].[Registrants]  

DELETE  FROM [registrationdb].[dbo].[Registrants]


SELECT TOP (1000) [Id]
      ,[FirstName]
      ,[MiddleName]
      ,[LastName]
      ,[Address]
      ,[AddressLine1]
      ,[AddressLine2]
      ,[City]
      ,[State]
      ,[PostalCode]
      ,[Email]
      ,[MobileNumber]
      ,[GovtId]
      ,[GovtIdLast4Digits]
      ,[OccupationStatus]
      ,[CompanyName]
      ,[LinkedInProfile]
      ,[GitHubProfile]
      ,[EducationalInstituteName]
      ,[GenderIdentity]
      ,[SelfDescribeGender]
      ,[AgeRange]
      ,[Ethnicity]
      ,[SelfDescribeEthnicity]
      ,[LanguageProficiency]
      ,[SelfDescribeLanguage]
      ,[EducationalBackground]
      ,[SelfDescribeEducation]
      ,[Disability]
      ,[DisabilityDetails]
      ,[DietaryRequirements]
      ,[SelfDescribeDietary]
      ,[LgbtqIdentity]
      ,[ParentalStatus]
      ,[FirstTimeAttendee]
      ,[HowDidYouHear]
      ,[SelfDescribeHowDidYouHear]
      ,[AreasOfInterest]
      ,[SelfDescribeAreasOfInterest]
      ,[VolunteerOpportunities]
      ,[AdditionalSupport]
      ,[Religion]
      ,[Caste]
      ,[Neighborhood]
      ,[ModeOfTransportation]
      ,[IsProfileComplete]
      ,[ProfileCompletedAt]
      ,[IsAideProfileComplete]
      ,[AideProfileCompletedAt]
      ,[GovtIdType]
  FROM [registrationdb].[dbo].[Registrants]


  DELETE FROM [registrationdb].[dbo].[Registrants]
  WHERE [Id] = <ID>';